### ISSUE TITLE
gtk-update-icon-cache: The generated cache was invalid

### ISSUE THREAD

**Issue by thyeun** [Ampiflow/Halo#3]
getting this message while update icon cache ```gtk-update-icon-cache: The generated cache was invalid```

**Comment by erikdubois** [comment]
what needs to be done is delete all or rename any files that have a space in them

**Comment by erikdubois** [comment]
ls -R | grep ' '

**Comment by thyeun** [comment]
thanks for the answer, i'm not sure how i manage to make it disappear but now the manage never appear since after a few days i posted here.
